import { ProtectedPage } from "@/components/ProtectedPage";
import TableCities from "@/components/table-cities";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cities | CRM Pogodka",
  description: "Generated by create next app",
};

export default function CitiesPage() {
  return (
    <ProtectedPage allowedRoles={["admin", "editor"]}>
      <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
        <TableCities />
      </div>
    </ProtectedPage>
  );
}
